<a href="https://colab.research.google.com/github/ajaychinni/summarization_transformer/blob/master/T5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install transformers

     |████████████████████████████████| 1.0MB 2.9MB/s 
     |████████████████████████████████| 890kB 14.5MB/s 
     |████████████████████████████████| 3.0MB 19.1MB/s 
     |████████████████████████████████| 1.1MB 43.8MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=b51f16c98b727be8da0702ba54c36cedb4a869954a2f22435f4b99d145d0ad0a
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [ ]:
from transformers import TFT5PreTrainedModel, T5Tokenizer, TFT5Model,TFT5ForConditionalGeneration
import tensorflow as tf

# model.generate

In [ ]:
paragraph ="""Since 2013 he divides his time working for Google (Google Brain) and the University of Toronto. 
In 2017, he cofounded and became the Chief Scientific Advisor of the Vector Institute in Toronto. Geoffrey Everest Hinton was on born 6 December 1947. He is an English Canadian cognitive 
psychologist and computer scientist, most noted for his work on artificial neural networks. 
Since 2013 he divides his time working for Google (Google Brain) and the University of Toronto. 
In 2017, he cofounded and became the Chief Scientific Advisor of the Vector Institute in Toronto. """

In [ ]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")
model = TFT5ForConditionalGeneration.from_pretrained('t5-small', return_dict=True)
inputs = tokenizer.encode(paragraph, return_tensors="tf")
result = model.generate(inputs)

All model checkpoint weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


In [ ]:
result

<tf.Tensor: shape=(1, 20), dtype=int32, numpy=
array([[    0, 32099,    19,    46,  1566,  4151, 12368, 21782,    11,
         1218, 17901,     6,   167,  4466,    21,   112,   161,    30,
         7353, 24228]], dtype=int32)>

In [ ]:
print(tokenizer.decode(result[0]))

<extra_id_0> is an English Canadian cognitive psychologist and computer scientist, most noted for his work on artificial neural


# Model

In [ ]:
paragraph = """My name is Ajay. I have 2 years of experince in machine leanrning and recntly 
        started exploring Hugging face library. I will be continuing my journey in exploring and learn
        something new everyday let it be something realted to NLP, Mlops, or some inner worikings of 
        a transformer."""

In [ ]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")
#model = TFT5Model.from_pretrained("t5-small")
model = TFT5ForConditionalGeneration.from_pretrained('t5-small', return_dict=True)

All model checkpoint weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


In [ ]:
# input_ids = tokenizer.encode(paragraph, return_tensors="tf")
input_ids = tokenizer.encode(paragraph, return_tensors="tf")  # Batch size 1

In [ ]:
print(type(input_ids))
input_ids

<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(1, 74), dtype=int32, numpy=
array([[  499,   564,    19,    71,  1191,    63,     5,    27,    43,
          204,   203,    13,  1215,  4267,  3772,    16,  1437,    90,
          152,    52,    29,    53,    11,  5026,    29,    17,   120,
          708,  6990, 11560,  3896,   522,  3595,     5,    27,    56,
           36,  6168,    82,  2027,    16,  6990,    11,   669,   424,
          126,  4604,   752,    34,    36,   424,   490,  1054,    12,
          445,  6892,     6,   283,  8745,     7,     6,    42,   128,
         4723,  2275,  9629,    53,     7,    13,     3,     9, 19903,
            5,     1]], dtype=int32)>

In [ ]:
outputs = model(input_ids, decoder_input_ids=input_ids)

In [ ]:
outputs  

# Flask


In [ ]:
!pip install flask-ngrok

In [ ]:
html_page =  """<html>
<head>
<title>First app</title>
</head>
<body>
<h1> Flask app from Google Colab <h1>
</body>
</html>"""

In [ ]:
# demo flask app in google colab using flask-ngrok library
from flask import Flask
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)

@app.route("/")
def hello():
    return html_page

app.run()


In [ ]:
html_page =  """<html>
<head>
<title>First app</title>
</head>
<body>
<h1> Hugging Face T5 model summarization<h1>
<input type="text" name = "first">
</body>
</html>"""

In [ ]:
app = Flask(__name__)
run_with_ngrok(app)

@app.route("/")
def get_summary():
    return 

app.run()

Pipeline (BART)

In [2]:
from transformers import pipeline

In [3]:
summarizer = pipeline("summarization")

In [14]:
ARTICLE ="""After his PhD he worked at the University of Sussex, and (after difficulty finding funding in Britain)[27] the University of California, San Diego, and Carnegie Mellon University.[1] He was the founding director of the Gatsby Charitable Foundation Computational Neuroscience Unit at University College London,[1] and is currently[28] a professor in the computer science department at the University of Toronto. He holds a Canada Research Chair in Machine Learning, and is currently an advisor for the Learning in Machines & Brains program at the Canadian Institute for Advanced Research. Hinton taught a free online course on Neural Networks on the education platform Coursera in 2012.[29] Hinton joined Google in March 2013 when his company, DNNresearch Inc., was acquired. He is planning to "divide his time between his university research and his work at Google".[30]

Hinton's research investigates ways of using neural networks for machine learning, memory, perception and symbol processing. He has authored or co-authored over 200 peer reviewed publications.[2][31]

While Hinton was a professor at Carnegie Mellon University (1982–1987), David E. Rumelhart and Hinton and Ronald J. Williams applied the backpropagation algorithm to multi-layer neural networks. Their experiments showed that such networks can learn useful internal representations of data.[14] In an interview of 2018,[32] Hinton said that "David E. Rumelhart came up with the basic idea of backpropagation, so it's his invention." Although this work was important in popularizing backpropagation, it was not the first to suggest the approach.[15] Reverse-mode automatic differentiation, of which backpropagation is a special case, was proposed by Seppo Linnainmaa in 1970, and Paul Werbos proposed to use it to train neural networks in 1974.[15]

During the same period, Hinton co-invented Boltzmann machines with David Ackley and Terry Sejnowski.[33] His other contributions to neural network research include distributed representations, time delay neural network, mixtures of experts, Helmholtz machines and Product of Experts. In 2007 Hinton coauthored an unsupervised learning paper titled Unsupervised learning of image transformations.[34] An accessible introduction to Geoffrey Hinton's research can be found in his articles in Scientific American in September 1992 and October 1993.[35]

In October and November 2017 respectively, Hinton published two open access research papers[36][37] on the theme of capsule neural networks, which according to Hinton are "finally something that works well."[38]

Notable former PhD students and postdoctoral researchers from his group include Peter Dayan,[39] Sam Roweis,[39] Richard Zemel,[3][6] Brendan Frey,[7] Radford M. Neal,[8] Ruslan Salakhutdinov,[9] Ilya Sutskever,[10] Yann LeCun[40] and Zoubin Ghahramani. Since 2013 he divides his time working for Google (Google Brain) and the University of Toronto. 
In 2017, he cofounded and became the Chief Scientific Advisor of the Vector Institute in Toronto. Geoffrey Everest Hinton was on born 6 December 1947. He is an English Canadian cognitive 
psychologist and computer scientist, most noted for his work on artificial neural networks. 
Since 2013 he divides his time working for Google (Google Brain) and the University of Toronto. 
In 2017, he cofounded and became the Chief Scientific Advisor of the Vector Institute in Toronto."""

In [15]:
print(summarizer(ARTICLE, max_length=110, min_length=30, do_sample=False))

[{'summary_text': " Geoffrey Everest Hinton co-invented Boltzmann machines with David Ackley and Terry Sejnowski . Hinton's research investigates ways of using neural networks for machine learning, memory, perception and symbol processing . He joined Google in March 2013 when his company, DNNresearch Inc., was acquired ."}]


In [6]:
print(summarizer(ARTICLE, max_length=110, min_length=30, do_sample=False))

Your max_length is set to 120, but you input_length is only 119. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)


[{'summary_text': ' Geoffrey Everest Hinton was on born 6 December 1947 . He is an English Canadian cognitive psychologist and computer scientist . He cofounded and became the Chief Scientific Advisor of the Vector Institute in Toronto .'}]


T5

In [7]:
from transformers import TFAutoModelWithLMHead, AutoTokenizer

In [8]:
model = TFAutoModelWithLMHead.from_pretrained("t5-base")
tokenizer = AutoTokenizer.from_pretrained("t5-base")

/usr/local/lib/python3.6/dist-packages/transformers/modeling_tf_auto.py:695: FutureWarning: The class `TFAutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `TFAutoModelForCausalLM` for causal language models, `TFAutoModelForMaskedLM` for masked language models and `TFAutoModelForSeq2SeqLM` for encoder-decoder models.
  FutureWarning,


All model checkpoint weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


In [16]:
inputs = tokenizer.encode("summarize: " + ARTICLE, return_tensors="tf", max_length=512)
outputs = model.generate(inputs, max_length=150, min_length=40, length_penalty=2.0, num_beams=4, early_stopping=True)

Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [13]:
tokenizer.decode(outputs[0])

'Geoffrey Everest Hinton is an English Canadian cognitive psychologist and computer scientist. he divides his time working for Google (Google Brain) and the University of Toronto. in 2017, he cofounded and became the Chief Scientific Advisor of the Vector Institute.'

In [17]:
tokenizer.decode(outputs[0])

'he has authored or co-authored over 200 peer reviewed publications. he is planning to "divide his time between his university research and his work at Google" he holds a Canada Research Chair in Machine Learning.'