<a href="https://colab.research.google.com/github/ajaychinni/summarization_transformer/blob/master/T5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install transformers

     |████████████████████████████████| 1.0MB 2.8MB/s 
     |████████████████████████████████| 3.0MB 18.8MB/s 
     |████████████████████████████████| 890kB 30.1MB/s 
     |████████████████████████████████| 1.1MB 42.5MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=f58501e98a1db65345178c95b81c568537f1e29678a2f492a23b9732ff29494a
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [2]:
from transformers import TFT5PreTrainedModel, T5Tokenizer, TFT5Model,TFT5ForConditionalGeneration
import tensorflow as tf

# model.generate

In [3]:
paragraph ="""Since 2013 he divides his time working for Google (Google Brain) and the University of Toronto. 
In 2017, he cofounded and became the Chief Scientific Advisor of the Vector Institute in Toronto. Geoffrey Everest Hinton was on born 6 December 1947. He is an English Canadian cognitive 
psychologist and computer scientist, most noted for his work on artificial neural networks. 
Since 2013 he divides his time working for Google (Google Brain) and the University of Toronto. 
In 2017, he cofounded and became the Chief Scientific Advisor of the Vector Institute in Toronto. """

In [4]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")
model = TFT5ForConditionalGeneration.from_pretrained('t5-small', return_dict=True)
inputs = tokenizer.encode(paragraph, return_tensors="tf")
result = model.generate(inputs)

All model checkpoint weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


In [5]:
result

<tf.Tensor: shape=(1, 20), dtype=int32, numpy=
array([[    0, 32099,    19,    46,  1566,  4151, 12368, 21782,    11,
         1218, 17901,     6,   167,  4466,    21,   112,   161,    30,
         7353, 24228]], dtype=int32)>

In [6]:
print(tokenizer.decode(result[0]))

<extra_id_0> is an English Canadian cognitive psychologist and computer scientist, most noted for his work on artificial neural


# Model

In [ ]:
paragraph = """My name is Ajay. I have 2 years of experince in machine leanrning and recntly 
        started exploring Hugging face library. I will be continuing my journey in exploring and learn
        something new everyday let it be something realted to NLP, Mlops, or some inner worikings of 
        a transformer."""

In [ ]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")
#model = TFT5Model.from_pretrained("t5-small")
model = TFT5ForConditionalGeneration.from_pretrained('t5-small', return_dict=True)

All model checkpoint weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


In [ ]:
# input_ids = tokenizer.encode(paragraph, return_tensors="tf")
input_ids = tokenizer.encode(paragraph, return_tensors="tf")  # Batch size 1

In [ ]:
print(type(input_ids))
input_ids

<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(1, 74), dtype=int32, numpy=
array([[  499,   564,    19,    71,  1191,    63,     5,    27,    43,
          204,   203,    13,  1215,  4267,  3772,    16,  1437,    90,
          152,    52,    29,    53,    11,  5026,    29,    17,   120,
          708,  6990, 11560,  3896,   522,  3595,     5,    27,    56,
           36,  6168,    82,  2027,    16,  6990,    11,   669,   424,
          126,  4604,   752,    34,    36,   424,   490,  1054,    12,
          445,  6892,     6,   283,  8745,     7,     6,    42,   128,
         4723,  2275,  9629,    53,     7,    13,     3,     9, 19903,
            5,     1]], dtype=int32)>

In [ ]:
outputs = model(input_ids, decoder_input_ids=input_ids)

In [ ]:
outputs  

# Flask


In [ ]:
!pip install flask-ngrok

In [14]:
html_page =  """<html>
<head>
<title>First app</title>
</head>
<body>
<h1> Flask app from Google Colab <h1>
</body>
</html>"""

In [ ]:
# demo flask app in google colab using flask-ngrok library
from flask import Flask
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)

@app.route("/")
def hello():
    return html_page

app.run()


In [18]:
html_page =  """<html>
<head>
<title>First app</title>
</head>
<body>
<h1> Hugging Face T5 model summarization<h1>
<input type="text" name = "first">
</body>
</html>"""

In [19]:
app = Flask(__name__)
run_with_ngrok(app)

@app.route("/")
def get_summary():
    return 

app.run()