<a href="https://colab.research.google.com/github/ajaychinni/summarization_transformer/blob/master/T5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install transformers

In [2]:
from transformers import TFT5PreTrainedModel, T5Tokenizer, TFT5Model,TFT5ForConditionalGeneration
import tensorflow as tf

# model.generate

In [25]:
paragraph ="""Since 2013 he divides his time working for Google (Google Brain) and the University of Toronto. 
In 2017, he cofounded and became the Chief Scientific Advisor of the Vector Institute in Toronto. Geoffrey Everest Hinton was on born 6 December 1947. He is an English Canadian cognitive 
psychologist and computer scientist, most noted for his work on artificial neural networks. 
Since 2013 he divides his time working for Google (Google Brain) and the University of Toronto. 
In 2017, he cofounded and became the Chief Scientific Advisor of the Vector Institute in Toronto. """

In [ ]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")
model = TFT5ForConditionalGeneration.from_pretrained('t5-small', return_dict=True)
inputs = tokenizer.encode(paragraph, return_tensors="tf")
result = model.generate(inputs)

In [28]:
result

<tf.Tensor: shape=(1, 20), dtype=int32, numpy=
array([[    0, 32099,    19,    46,  1566,  4151, 12368, 21782,    11,
         1218, 17901,     6,   167,  4466,    21,   112,   161,    30,
         7353, 24228]], dtype=int32)>

In [29]:
print(tokenizer.decode(result[0]))

<extra_id_0> is an English Canadian cognitive psychologist and computer scientist, most noted for his work on artificial neural


# Model

In [30]:
paragraph = """My name is Ajay. I have 2 years of experince in machine leanrning and recntly 
        started exploring Hugging face library. I will be continuing my journey in exploring and learn
        something new everyday let it be something realted to NLP, Mlops, or some inner worikings of 
        a transformer."""

In [31]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")
#model = TFT5Model.from_pretrained("t5-small")
model = TFT5ForConditionalGeneration.from_pretrained('t5-small', return_dict=True)

All model checkpoint weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


In [32]:
# input_ids = tokenizer.encode(paragraph, return_tensors="tf")
input_ids = tokenizer.encode(paragraph, return_tensors="tf")  # Batch size 1

In [33]:
print(type(input_ids))
input_ids

<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(1, 74), dtype=int32, numpy=
array([[  499,   564,    19,    71,  1191,    63,     5,    27,    43,
          204,   203,    13,  1215,  4267,  3772,    16,  1437,    90,
          152,    52,    29,    53,    11,  5026,    29,    17,   120,
          708,  6990, 11560,  3896,   522,  3595,     5,    27,    56,
           36,  6168,    82,  2027,    16,  6990,    11,   669,   424,
          126,  4604,   752,    34,    36,   424,   490,  1054,    12,
          445,  6892,     6,   283,  8745,     7,     6,    42,   128,
         4723,  2275,  9629,    53,     7,    13,     3,     9, 19903,
            5,     1]], dtype=int32)>

In [34]:
outputs = model(input_ids, decoder_input_ids=input_ids)

In [35]:
outputs  

TFSeq2SeqLMOutput([('logits',
                    <tf.Tensor: shape=(1, 74, 32128), dtype=float32, numpy=
                    array([[[-31.687735 , -10.278185 , -14.327241 , ..., -48.285595 ,
                             -48.241184 , -48.30368  ],
                            [-32.349052 ,  -9.583202 , -13.724545 , ..., -50.867302 ,
                             -50.81259  , -50.881203 ],
                            [-35.402447 , -13.4181385, -17.199432 , ..., -56.299797 ,
                             -56.392563 , -56.40464  ],
                            ...,
                            [-51.038498 , -15.436643 , -23.006435 , ..., -68.542076 ,
                             -68.72765  , -68.62229  ],
                            [-31.86594  ,  -4.5202036, -14.252811 , ..., -47.112576 ,
                             -47.207943 , -47.15904  ],
                            [-23.661854 ,  -2.9694536,  -8.94923  , ..., -39.262276 ,
                             -39.285824 , -39.240486 ]]], dtype=f